### ISSUE TITLE
Locally installed package does not work 

### ISSUE THREAD

**Issue by stefaneg** [stefaneg/yamrt#1]
Error: Cannot find module 'rc'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gulli/src/github.com/shepherd/npm-libraries/node_modules/yamrt/src/registry-package-info/registry-package-info.js:1:74)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gulli/src/github.com/shepherd/npm-libraries/node_modules/yamrt/src/package-augment/get-npmjs-package-info.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! packages@ build: `yamrt ./packages`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the packages@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by stefaneg** [comment]
yamrt should work when installed locally, not only globally.
